=== akshaksh/MyProjects/Oxygen Workspace/ManishSirProgramProjects/Address.dtd
<!ELEMENT addressbook (contact)>
<!ELEMENT contact (name,address+,city,state,zip,phone,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!--Space is mandatory between tag name and bracker of parsing data-->

=== akshaksh/MyProjects/Oxygen Workspace/ManishSirProgramProjects/Address.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE addressbook SYSTEM "Address.dtd" >
<addressbook>
  <contact>
    <name>name</name>
    <address>address</address>
    <city>city</city>
    <state>state</state>
    <zip>zip</zip>
    <phone>phone</phone>
    <email>email</email>
  </contact>
  <contact>
    <name>name</name>
    <address>address</address>
    <city>city</city>
    <state>state</state>
    <zip>zip</zip>
    <phone>phone</phone>
    <email>email</email>
  </contact>
  <contact>
    <name>name</name>
    <address>address</address>
    <city>city</city>
    <state>state</state>
    <zip>zip</zip>
    <phone>phone</phone>
    <email>email</email>
  </contact>
</addressbook>
